### PR TITLE
Remove three unnecessary bitmasks

### PR DESCRIPTION
**Pull request by TedLyngmo**
Remove the bitmask from the first utf8 octet for codepoints > 0x7f. The range check and bit shift already makes sure that the result is ok.

### CODE REVIEW

**Comment by TedLyngmo** [comment]
Question: My re2c generated json.hpp ends up looking very different from yours. I have to edit it by hand afterwards to remove trailing spaces and to get the proper indenting. I'm using [https://github.com/skvadrik/re2c]. Which re2c are you using?

**Comment by nlohmann** [comment]
@TedLyngmo You can run "make pretty" which uses Astyle http://astyle.sourceforge.net/. I am using re2c 0.16.

**Comment by TedLyngmo** [comment]
Ah, ok, great, that worked :-) Btw, I don't know how to interpret the pending coverage check. It seems to be finished but has no data?

**Comment by nlohmann** [comment]
I also have no idea about coveralls. If you add a commit with "make pretty", it should trigger another check.

**Comment by TedLyngmo** [comment]
Utterly confusing ... It's stuck again although the job is finished. I'll close this and create another branch.

**Pull request closed without merging**
