### PR TITLE
Add NLOHMANN_DEFINE_DERIVED_TYPE_* macros

### LINKED ISSUE #2199: How to Serialize derived class to JSON object?
#### What do you want to achieve?

I'm trying to serialize my objects. They look like this (overly simplified):
```
class A {
 double Aa;
 double Ab;
};

class B : public A{
  int Ba;
  int Bb;
};
```

#### What have you tried?

I'm trying to create a JSON object like this:
```
B = {
 "Aa": 1.0,
 "Ab": 2.0,
 "Ba": 3,
 "Bb": 4
}
```
#### Can you provide a small code example?
```
inline void to_json( nlohmann::json& JSON, const A& a ) {
  JSON = { "Aa", a.Aa, "Ab", a.Ab };
}
inline void to_json( nlohmann::json& JSON, const B& b ) {
 // how to call the base class(A)'s to_json and from_json function?
  JSON = { "Ba", b.Ba, "Bb", b.Bb };
}
```
Please help me know how to call the base class's to_json and from_json function.

Describe which system (OS, compiler) you are using.
LLVM 3.8.1

Describe which version of the library you are using (release version, develop branch).
Fairly recent from master branch.

### PR DESCRIPTION
**Pull request by rotolof**
I created the new macros:
- `NLOHMANN_DEFINE_DERIVED_TYPE_INTRUSIVE`
- `NLOHMANN_DEFINE_DERIVED_TYPE_INTRUSIVE_WITH_DEFAULT`
- `NLOHMANN_DEFINE_DERIVED_TYPE_NON_INTRUSIVE`
- `NLOHMANN_DEFINE_DERIVED_TYPE_NON_INTRUSIVE_WITH_DEFAULT`

to recreate the proposed fix to #2199.
The macros accept as second parameter the base class.

Usage example:

```cpp
class A {
  double Aa;
  double Ab;
  NLOHMANN_DEFINE_TYPE_INTRUSIVE(A, Aa, Ab)
};

class B : public A {
  int Ba;
  int Bb;
  NLOHMANN_DEFINE_DERIVED_TYPE_INTRUSIVE(B, A, Ba, Bb)
};
```

What they do is basically calling the `to_json`/`from_json` functions of the base class before serialising/deserialising the class members:

```cpp
void to_json(nlohmann::json& j, const B& b) {
    nlohmann::to_json(j, static_cast<const A&>(b));
    // ...
}

void from_json(const nlohmann::json& j, B& b) {
    nlohmann::from_json(j, static_cast<A&>(b));
    // ...
}
```

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

### CODE REVIEW

**Comment by hacker-cb** [comment]
Any updates about this PR?

**Comment by rotolof** [comment]
I just solved the conflict that had arisen in the meantime.

**Comment by nlohmann** [comment]
I am currently finishing #2998 to finally have a stable CI. Once this is merged, please update your branch.

**Review by nlohmann — CHANGES_REQUESTED** [review]
Please add documentation. See https://github.com/nlohmann/json/blob/develop/docs/mkdocs/docs/api/macros/index.md for a starting point.

**Comment by nlohmann** [comment]
(Also, please update from the develop branch and fix the conflicts.)

**Comment by eyalk1** [comment]
since this code now actually modifies the json object from base -  what do you guys think about using ```merge_patch``` or ```+=``` instead of ```=``` for each member?
for example:
```cpp
#define NLOHMANN_JSON_PAIR(member) {#member, nlohmann_json_t.member},

#define NLOHMANN_INIT_PAIRS(...)                                               \
  NLOHMANN_JSON_EXPAND(NLOHMANN_JSON_PASTE(NLOHMANN_JSON_PAIR, __VA_ARGS__))

#define NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_INHERITANCE(derived, base, ...)     \
  void to_json(nlohmann::json &nlohmann_json_j,                                \
               derived const &nlohmann_json_t) {                               \
    to_json(nlohmann_json_j, static_cast<base const &>(nlohmann_json_t));      \
    nlohmann_json_j.merge_patch(nlohmann::json{                                \
        NLOHMANN_JSON_EXPAND(NLOHMANN_INIT_PAIRS(__VA_ARGS__))});              \
  }                                                                            \
  void from_json(nlohmann::json const &nlohmann_json_j,                        \
                 derived &nlohmann_json_t) {                                   \
    from_json(nlohmann_json_j, static_cast<base &>(nlohmann_json_t));          \
    NLOHMANN_JSON_EXPAND(NLOHMANN_JSON_PASTE(NLOHMANN_JSON_FROM, __VA_ARGS__)) \
  }
```

**Comment by rotolof** [comment]
I updated to the latest develop and added documentation, let me know it is ok now

**Comment by gregmarr** [comment]
@rotolof Looks like you might be using a different version of astyle (perhaps even a newer one) which has different behavior than the current version being used.  https://github.com/nlohmann/json/pull/4180#issuecomment-1758627278

**Comment by rotolof** [comment]
@gregmarr Thanks, I was using macOS brew's astyle that is 3.4.9. I tried with the suggested 3.1 but it does not support `squeeze-lines`, wtf?

**Comment by nlohmann** [comment]
Comment that line from the config and try again. Sorry for the inconvenience - I did not find the time to fix this yet.

**Comment by RubberDuckAcolyte** [comment]
Are there any chances to release that soon? Seems like the most of work has been done and it just hanging almost a year now.

**Comment by rotolof** [comment]
> Are there any chances to release that soon? Seems like the most of work has been done and it just hanging almost a year now.

Sorry, I completely forgot about this until now! Let me check it again.

**Comment by RubberDuckAcolyte** [comment]
Is this change ok now? Can it possibly be integrated soon?

**Comment by rotolof** [comment]
> Is this change ok now? Can it possibly be integrated soon?

I think that everything is fine, I had updated with the latest develop and all checks had passed, is anything missing @nlohmann?

**Comment by ncanderson** [comment]
Would love to see this released too.

**Comment by RubberDuckAcolyte** [comment]
@nlohmann can you please relate to this changes? Can we release that? It's ready from half a year now...

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Thanks!

**Pull request merged**
