### PR TITLE
Add CPack support

### PR DESCRIPTION
**Pull request by zjyhjqs**

### CODE REVIEW

**Comment by zjyhjqs** [comment]
@nlohmann Do you have question about this PR?

**Comment by nlohmann** [comment]
> @nlohmann Do you have question about this PR?

Why is this addition needed?

**Comment by zjyhjqs** [comment]
> Why is this addition needed?

The CPack module is necessary for users to use CPack to package the library. (The main information required by cpack is provided by `project()`. Just including the CPack module is enough.)

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Pull request merged**
