### PR TITLE
fix #414 - comparing to 0 literal

### LINKED ISSUE #414: comparing to 0 literal
Hello,

Comparing to the 0 literal results calls `operator==(const_reference v, std::nullptr_t)` since converting to a standard type is preferred to a custom one (json).

```cpp
// don't let catch decompose the expression
CHECK((json(0) == 0));
CHECK((0 == json(0)));
```

### PR DESCRIPTION
**Pull request by stanmihai4**
Add a function overload for comparing to int, so that the 0 literal is not converted to nullptr.

### CODE REVIEW

**Comment by nlohmann** [comment]
Please fix this PR - when I remove the functions `friend bool operator==(const_reference v, std::nullptr_t) noexcept` and `friend bool operator==(std::nullptr_t, const_reference v) noexcept`, I cannot compile the tests any more:

```
[CXXLD] test-cbor
src/unit-cbor.cpp:31:9: warning: keyword is hidden by macro definition
      [-Wkeyword-macro]
#define private public
        ^
src/unit-cbor.cpp:747:29: error: use of overloaded operator '==' is ambiguous
      (with operand types 'json' (aka 'basic_json<>') and 'nullptr_t')
                    CHECK(j == nullptr);
                          ~ ^  ~~~~~~~
thirdparty/catch/catch.hpp:10503:44: note: expanded from macro 'CHECK'
#define CHECK( expr ) INTERNAL_CATCH_TEST( expr, Catch::ResultDispositio...
                                           ^~~~
thirdparty/catch/catch.hpp:2083:41: note: expanded from macro
      'INTERNAL_CATCH_TEST'
    } while( Catch::isTrue( false && !!(expr) ) ) // expr here is never ...
                                        ^~~~
../src/json.hpp:5580:17: note: candidate function
    friend bool operator==(const_reference lhs, const_reference rhs) noexcept
                ^
src/unit-cbor.cpp:747:29: note: built-in candidate operator==(nullptr_t,
      nullptr_t)
                    CHECK(j == nullptr);
                            ^
```

**Comment by stanmihai4** [comment]
Do you have an update on what will happen to this PR ?

**Comment by nlohmann** [comment]
@stanmihai4 Sorry, i did not find the time for this PR. I shall definitely have a look before the next release!

**Comment by nlohmann** [comment]
Thanks a lot @stanmihai4! I merged this branch with 057b1e606b0f3c1da222c4e0094c20d7f4aa426e.

**Pull request merged**
