### PR TITLE
Fix issue#1275

### PR DESCRIPTION
**Pull request by dota17**
Fix issue #1275 : add an overload of  function `value(key, default_value)`.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

### CODE REVIEW

**Comment by dota17** [comment]
@FrancoisChabot thank your advices! I think the first point is better, cause the second one will wait until the next major release, that will be a very long time. And the third one, I think it isn't the thing about the range of the default value.
But right now, I haven't got a new function name, I saw someone proposed to name `pop_value()`, 
how do you think?

**Comment by nlohmann** [comment]
I'm against breaking the API, and I am not really convinced that adding a new function is really helpful. This is a very small corner case, and it is possible to implement it via the public API.

**Comment by dota17** [comment]
Ok, I will not add a new function to break the API, but only focus on 3).
But I am confused with the meaning of expanding the range of the default_value.

**Comment by dota17** [comment]
@nlohmann @FrancoisChabot Are you satisfied with the last changes?

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Allow r-values in `value` function. #1275 #2181

* * *

**Comment by lethe555** [comment]
just break my code
```
json j{{"x", "test"}};
std::string defval = "default value";
auto val = j.value("x",defval);
auto val2 = j.value("y",defval);
```
json.hpp:19714:25: warning: returning reference to temporary [-Wreturn-local-addr]
                 return *it;

**Comment by gregmarr** [comment]
@lethe555 Which line is 19714?  Assuming it's the `return *it`, you haven't shown us what `it` is.

**Comment by lethe555** [comment]
@gregmarr 
```
json j{{"x", "test"}};
std::string defval = "default value";
auto val = j.value("x",defval);
auto val2 = j.value("y",defval);
```
error: no matching function for call to 'nlohmann::basic_json<>::value(const char [2], std::string&)'
     auto val = j.value("x", defval);

 now default_value seems can't be a lvalue , but use a lvalue as default value is very common case

**Comment by nlohmann** [comment]
I can confirm that the code in https://github.com/nlohmann/json/pull/2181#issuecomment-655448399 does not compile with the latest develop version. Reason is this PR. I shall revert the changes and add a regression test. Then, we can decide how to properly address #1275.

**Comment by nlohmann** [comment]
Done.

**Comment by gregmarr** [comment]
I think you might be able to do this same basic PR but using `std::forward` instead of `std::move`.

**Comment by nlohmann** [comment]
I can't get it to run:

```
../test/src/unit-regression.cpp:1954:22: error: no matching member function for call to 'value'
        auto val = j.value("x", defval);
                   ~~^~~~~
../include/nlohmann/json.hpp:3810:14: note: candidate function not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const char *' for 2nd argument
    string_t value(const typename object_t::key_type& key, const char* default_value) const
             ^
../include/nlohmann/json.hpp:3884:14: note: candidate function not viable: no known conversion from 'const char [2]' to 'const nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::json_pointer' (aka 'const json_pointer<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >') for 1st argument
    string_t value(const json_pointer& ptr, const char* default_value) const
             ^
../include/nlohmann/json.hpp:3788:15: note: candidate template ignored: requirement 'std::is_convertible<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &>::value' was not satisfied [with ValueType = std::__1::basic_string<char> &]
    ValueType value(const typename object_t::key_type& key, ValueType&& default_value) const
              ^
../include/nlohmann/json.hpp:3860:15: note: candidate template ignored: requirement 'std::is_convertible<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &>::value' was not satisfied [with ValueType = std::__1::basic_string<char> &]
    ValueType value(const json_pointer& ptr, ValueType&& default_value) const
```

**Comment by dota17** [comment]
@nlohmann 
Please see dota17#18, I made a new PR in my fork repo for this issue.
And from CI log, the test `SECTION("PR #2181 - regression bug with lvalue")` had no error for new PR.
I just added back the original method and then there would be two methods:
```
ValueType value(const typename object_t::key_type& key, const ValueType& default_value) const //  added back
...
ValueType value(const typename object_t::key_type& key, ValueType && default_value) const
```

If you think it works, I would push it to the official repo.

**Comment by nlohmann** [comment]
That would be great.

**Pull request merged**
