### PR TITLE
Parse streams incrementally.

### PR DESCRIPTION
**Pull request by aburgh**
I did not update `src/json.hpp` because I get different indentation results than the existing version.

### CODE REVIEW

**Comment by nlohmann** [comment]
Thanks a lot! I'll check this when I'm back from holidays.

**Comment by nlohmann** [comment]
Thanks a lot!

**Comment by aburgh** [comment]
Hi Niels,

Glad you found it worthwhile. Not to be too narcissistic, but since you are giving credit in the Readme can you put my name on it? (Unless I am misunderstanding Joshua Randall's contributions.)

Regards,

Aaron

**Comment by nlohmann** [comment]
Hi @aburgh,

I am so sorry! I'll update the README in a second. Again, thanks for the contribution! I'll also check the pull request #41 soon.

All the best
Niels

**Comment by aburgh** [comment]
No worries, thanks. And thanks again for the project. I'm still getting up to speed on C++, so this was educational. Your project also inspired me to try to adapt it for handling OS X plist files, which are similar to JSON, but have a date and data type, and can be serialized to/from XML and a proprietary binary format.

Cheers,

Aaron

**Pull request merged**
