### PR TITLE
Split test-unicode to avoid timeouts

### LINKED ISSUE #1032: Some testcases fail and one never finishes
```
      Start 10: test-cbor_all
10/78 Test #10: test-cbor_all .......................***Exception: Child aborted  9.98 sec
      Start 56: test-msgpack_all
56/78 Test #56: test-msgpack_all ....................***Exception: Child aborted  9.99 sec
      Start 74: test-ubjson_all
74/78 Test #74: test-ubjson_all .....................***Exception: Child aborted  2.96 sec
      Start 78: test-unicode_all
/// {never finishes}
```

OS: FreeBSD-11.1 amd64
Version 3.1.2 built from port, while trying to update it.

### LINKED ISSUE #1816: Semi-frequent timeouts in `test-unicode_all` with 3.6.1 (aarch64)
On a semi-regular basis, the `test-unicode_all` test times out in the NixOS build farm.

This is running NixOS on the host, with GCC 8.3.0.

Full build log available: https://hydra.nixos.org/build/103809502/nixlog/1

Log snippet:

```
88/88 Test #80: test-unicode_all ....................***Timeout 1500.01 sec
100000 of 8860608 UTF-8 strings checked
[...]
8200000 of 8860608 UTF-8 strings checked


99% tests passed, 1 tests failed out of 88

Label Time Summary:
all        = 1627.51 sec*proc (41 tests)
default    =  25.67 sec*proc (41 tests)

Total Test time (real) = 1548.32 sec

The following tests FAILED:
         80 - test-unicode_all (Timeout)
```

### PR DESCRIPTION
**Pull request by nickaein**
This PR splits the long-running `unit-test_all` into two standalone unit-tests.

Fixes #1816, fixes #1032 (hopefully).

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [ ]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [ ]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](http://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nickaein** [comment]
@nlohmann 

What do you think of this simple re-organization for test-unicode to partition its running time that could help fix issues like #1816 and #1032.

The pipeline has falied due to (ironically) exceeding Appveyor 1 hour limit. A re-run might fix that.

I've also tried to some micro-optimizations on implementation of [`check_utf8dump`](https://github.com/nlohmann/json/blob/0feea6168df847c3fc33a986cf8a6112b03e4ddd/test/src/unit-unicode.cpp#L52) and [`check_utf8string`](https://github.com/nlohmann/json/blob/0feea6168df847c3fc33a986cf8a6112b03e4ddd/test/src/unit-unicode.cpp#L127) but didn't find a significant improvement (yet).

**Comment by dota17** [comment]
@nickaein 
Currently, the test-unicode_all is always not finished because times out.
This often happens in Xcode 9.2 C++ and before.

I think this PR is a good try. We can reopen this one to solve the problem.

**Comment by nickaein** [comment]
@dota17 Can you test this branch locally to see whether it is effective in your case?

https://github.com/nickaein/nlohmann-json/tree/fix/split-unicode-tests

**Comment by nlohmann** [comment]
Can you please update to the latest `develop` branch - there have been several fixes with respect to the CI.

**Comment by dota17** [comment]
> Can you test this branch locally to see whether it is effective in your case?
https://github.com/nickaein/nlohmann-json/tree/fix/split-unicode-tests

Everything is fine in my local env.
It should be verified in this repo's travis-ci and currently, i had not find any error.

**Pull request closed without merging**
