### PR TITLE
appveyor.yml: Add MSVC 16 2019 support

### PR DESCRIPTION
**Pull request by t-b**
silence bot!

### CODE REVIEW

**Comment by t-b** [comment]
@nlohmann Ready

**Comment by t-b** [comment]
@nlohmann Anything still missing here

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Add MSVC 16 2019 support to CI.

* * *

**Pull request merged**
