### PR TITLE
appveyor.yml: Compile and test with latest version for __cplusplus ma…

### LINKED ISSUE #1695: /Zc:__cplusplus leads to C2416
OS: Windows 7
Compiler: MSVC 2017 (15.9.11)

If project uses `/Zc:__cplusplus` json lib v3.7.0 fails to compile with this:
```
C2416: attribute 'deprecated' cannot be applied in this context
```

Looks like MSVC doesn't like this attribute applied to operator>> definition.

### PR DESCRIPTION
**Pull request by t-b**
…cro on MSVC

According to [1] the C++ macro __cplusplus has always the value 199711L
even if you enable later version of C++ support via /std.

Use one job with /Zc:__cplusplus defined so that we know that it
compiles.

[1]: https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=vs-2019

I can't reopen https://github.com/nlohmann/json/pull/1810.

Close #1695.

### CODE REVIEW

**Comment by t-b** [comment]
@nlohmann Ready, I've included your hedley update already.

**Comment by dota17** [comment]
I had made a test and it is ok. I think this can be merged.

**Comment by t-b** [comment]
@nlohmann Can we merge this?

**Comment by nlohmann** [comment]
Could you please rebase to the latest develop branch?

**Comment by t-b** [comment]
@nlohmann Done.

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Use `/Zc:__cplusplus` in the AppVeyor CI for latest version of MSVC. #1695 #1810 #1958

* * *

**Pull request merged**
