### PR TITLE
 test (non)equality for alt_string implementation 

### PR DESCRIPTION
**Pull request by agrianius**
Add a bit more tests for alt_string implementation

### CODE REVIEW

**Comment by agrianius** [comment]
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.9 valgrind ninja-build" failed and exited with 100 during .

Seems like a network problem. How to relaunch the tests?

**Comment by theodelrieu** [comment]
Yes it happens sometimes, you can run:

```shell
git commit --amend --no-edit && git push --force
```

**Comment by agrianius** [comment]
Yes. I found that some revisions of the library fail this tests (I'm using similar logic in my application).

**Comment by nlohmann** [comment]
Thanks!

**Pull request merged**
