### PR TITLE
Fix issue #380: Signed integer overflow check

### PR DESCRIPTION
**Pull request by qwename**
See issue #380.

### CODE REVIEW

**Comment by qwename** [comment]
Previously, `json::parse("166020696663385964490").dump()` gave 18446744073709551562. Now it gives 1.66020696663386e+20.

**Comment by qwename** [comment]
Off-topic, but I had to compile the latest re2c (0.16) as Fedora 25 only provided 0.14.3, which didn't have the `-W` option. The option was added in 0.15, so this might be useful to add in `.github/CONTRIBUTING.md` http://re2c.org/news/changelog/changelog.html.

It seems like the new version also reduced the generated code length.

**Comment by TurpentineDistillery** [comment]
Or, one could make changes to the .hpp, and then have a pre-commit hook do
`git checkout src/json.hpp.re2c && git diff src/json.hpp | patch src/json.hpp.re2c`

**Comment by nlohmann** [comment]
@qwename Thanks for the hint on the re2c version. I shall add a note to the contributing file. For the whitespace, you may want to execute `make pretty` which uses [astyle](http://astyle.sourceforge.net).

**Comment by qwename** [comment]
I missed the part about `make pretty`, fixed it now.

**Comment by nlohmann** [comment]
There are some conversion warnings. Can you fix them?

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
Thanks! I shall add a regression test for `166020696663385964490`.

**Pull request merged**
