### PR TITLE
Adds instruction for using Build2's package manager

### PR DESCRIPTION
**Pull request by Klaim**
I created a `nlohmann-json` package for `build2` (https://build2.org) that have been published on the central public repository https://cppget.org : https://cppget.org/nlohmann-json (at the moment you can see that there is only one version: 3.7.3).

The repository of the package code is there: https://github.com/build2-packaging/nlohmann-json and is owned by the build2 community now. (with build2 you can use either a repository like cppget.org or a git repository so both are useful to users for different use cases).

This patch just add the basic information as to how to use this library with build2 to the README file. This is documentation-only.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](http://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
Thanks a lot! I'll merge once the Travis CI succeeds.

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Add support for the build2 package manager. #1909

* * *

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
Hi @Klaim, it's been a while that you added the description for build2. Meanwhile, we created a dedicated documentation page for all supported package managers: https://json.nlohmann.me/integration/package_managers/

Unfortunately, I struggle to create a self-contained example how to compile a small example with build2. Can you support me here?

**Comment by Klaim** [comment]
Sure!

Looking at the other examples, the self-contained exampled should be "from scratch", that is we create a new project and add the library as a dependency. Do I understand correctly?

**Comment by nlohmann** [comment]
Awesome!

Yes, the idea is to show how to compile the given `example.cpp` with each package manager. In most cases, this boils down to creating a few other files and then call some commands to get the package and build the project.

**Comment by Klaim** [comment]
Yeah in the case of `build2` it's more usual to use [`bdep new ...`](https://build2.org/bdep/doc/bdep-new.xhtml) to create the new project as it will generate more files than people tend to expect (necessary for consuming packages + handling the project growing) and setup automatically depending on the options. Also at least one configuration need to be created (similar to cmake's build dir but with the dependencies downloaded and built in there too) for dependencies to be usable.

I'll make a PR soon 👍🏽  Maybe not today, probably tomorrow.

Should I also setup a "summary" box as you did with most other tools?

**Comment by nlohmann** [comment]
Yes, that would be awesome!

**Pull request merged**
