### PR TITLE
Fix CI issues

### LINKED ISSUE #3890: Check Drone CI
### Description

Drone CI jobs do not finish.

### Reproduction steps

Check any of the latest PRs.

### Expected vs. actual results

Drone CI job completes.

### Minimal code example

```Shell
N/A
```

### Error messages

```Shell
N/A
```

### Compiler and operating system

-

### Library version

develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by barcode**
I looked a bit at the [ci_test_compilers_clang (10)](https://github.com/nlohmann/json/actions/runs/3835776970/jobs/6529309030#logs) issue.
This PR did not change the affected test and it worked in [earlier builds](https://github.com/nlohmann/json/actions/runs/3777809193/jobs/6421841164).

It seems the compiler and changed to a newer version.

old:

    Compiler: clang version 10.0.0; Target: x86_64-unknown-linux-gnu; Thread model: posix; InstalledDir: /usr/local/bin

new:

    Compiler: Debian clang version 10.0.1-++20210313014605+ef32c611aa21-1~exp1~20210313125208.190; Target: x86_64-pc-linux-gnu; Thread model: posix; InstalledDir: /usr/bin

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [ x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x ]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

### CODE REVIEW

**Comment by barcode** [comment]
The error makes it pretty clear that `libstdc++-8` is used.

    /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/fs_path.h

but span is only supported starting with [libstdc++-10](https://en.cppreference.com/w/cpp/compiler_support/20).

I guess the old version of the docker container had this or a more recent version installed, but i can't confirm, since i don't know how to get the old version of the image.

**Comment by barcode** [comment]
@nlohmann 
[To get cirrus working](https://cirrus-ci.com/github/nlohmann/json) you need to add their app to the repo. (I don't have the permissions to do this)

Also the `.cirrus.yml` [has to be in the root dir of the repo.](https://github.com/cirruslabs/cirrus-ci-docs/discussions/1131)

**Comment by barcode** [comment]
It seems filesystem in `libstdc++-8` does not really work when linking (even though `-lstdc++fs` is set):

https://github.com/nlohmann/json/actions/runs/3922291644/jobs/6705139818

      [148/166] : && /usr/bin/clang++ -g -lstdc++fs tests/CMakeFiles/test_main.dir/src/unit.cpp.o tests/CMakeFiles/test-regression2_cpp20.dir/src/unit-regression2.cpp.o -o tests/test-regression2_cpp20   && :
      FAILED: tests/test-regression2_cpp20 
      : && /usr/bin/clang++ -g -lstdc++fs tests/CMakeFiles/test_main.dir/src/unit.cpp.o tests/CMakeFiles/test-regression2_cpp20.dir/src/unit-regression2.cpp.o -o tests/test-regression2_cpp20   && :
      ...
      /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
      ...
      /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/fs_path.h:545: undefined reference to 

To fix this we would need to build out own version of `libstdc++` (there are no backports for debian buster). I deactivated filesystem for `ci_test_compilers_clang (10)`, since building  `libstdc++` would take a lot of time in the runner.

Now we only need to finish replacing drone with cirrus. (Since cirrus is currently deactivated, I reactivated drone to prevent the checks from succeeding.)

**Comment by nlohmann** [comment]
> @nlohmann [To get cirrus working](https://cirrus-ci.com/github/nlohmann/json) you need to add their app to the repo. (I don't have the permissions to do this)

I just did this.

> Also the `.cirrus.yml` [has to be in the root dir of the repo.](https://github.com/cirruslabs/cirrus-ci-docs/discussions/1131)

This should be done after merging, right?

**Comment by barcode** [comment]
> I just did this.

Ok, now i have to figure out why cirrus does not want to build this branch...

> This should be done after merging, right?

This will be done by this PR. It was meant as an explanation why the cirrus file is not placed in `.github/external_ci`.

**Comment by barcode** [comment]
There is clearly some strangeness going on with cirrus. If i change the file and already have the [cirrus repo page](https://cirrus-ci.com/github/nlohmann/json) open It gets updated  with an entry:
Screenshot from 2023-01-29 21-35-00

When clicking on it i get a not found error and on reloading it disappears.

@nlohmann Maybe there is some setting you can change. (not sure what it would be, but maybe the repo setting `Require approval for builds from users without write permissions` is activated)

Just in case you do not find some setting, I will try to contact the cirrus support. Maybe they can help.

**Comment by nlohmann** [comment]
> There is clearly some strangeness going on with cirrus. If i change the file and already have the [cirrus repo page](https://cirrus-ci.com/github/nlohmann/json) open It gets updated with an entry: Screenshot from 2023-01-29 21-35-00
> 
> When clicking on it i get a not found error and on reloading it disappears.
> 
> @nlohmann Maybe there is some setting you can change. (not sure what it would be, but maybe the repo setting `Require approval for builds from users without write permissions` is activated)
> 
> Just in case you do not find some setting, I will try to contact the cirrus support. Maybe they can help.

This is how it looks like:

image

I switched on `Require approval for builds from users without write permissions`. Let me know if I should try anything else.

**Comment by barcode** [comment]
At least now the build job stays in https://cirrus-ci.com/github/nlohmann/json instead of disappearing again.
I tried setting it up in my fork, but there i got the same issues. The builds disappear (even a manually triggered one.
Maybe it has something to do with the current issues with github actions:
https://www.githubstatus.com/
>  Investigating - We are investigating reports of degraded performance for Actions.
Jan 30, 2023 - 12:07 UTC

**Comment by barcode** [comment]
@nlohmann can you try approving one of the jobs listed on https://cirrus-ci.com/github/nlohmann/json? Maybe this fixes some strangeness in their back end.

/edit
Ok, i figured it out..
I accidentally named the file ' .cirrus.yml' (there was a space at the start of the file name) and this confused cirrus-ci. 
Now the jobs do not disappear anymore.
@nlohmann can you turn of require approval?
I will fix the pipeline for cirrus.

**Comment by nlohmann** [comment]
Done. I approved three builds and then turned off approvals.

**Comment by barcode** [comment]
Great it seems like we finally have a working CI again.
Now this PR is ready for review.

**Review by nlohmann — COMMENTED** [review]
Looks good to me.

**Review by nlohmann — APPROVED** [review]

**Comment by nlohmann** [comment]
Thanks a lot!!!!!

**Pull request merged**
