### PR TITLE
Swift package manager support

### PR DESCRIPTION
**Pull request by richardtop**
Issue: https://github.com/nlohmann/json/issues/2802
Discussion: https://github.com/nlohmann/json/discussions/2806

This adds support for the Swift Package Manager on Apple platforms.

I had to add an empty file to make SPM build the target, as header-only targets are not currently supported in the Swift Packages.

Similar solution has been used in Apple's swift-numerics repository:
Discussion: https://forums.swift.org/t/header-only-library-using-swift-package-manager/42700
Repository: https://github.com/apple/swift-numerics/blob/main/Sources/_NumericsShims/_NumericsShims.c

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
Do all files need to be put into the repository root?

**Comment by richardtop** [comment]
As for now, this is impossible, as the "Swift Package" is defined as:
"a git repository with semantically versioned tags, that contains Swift sources and a Package.swift manifest file at its root."
https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-a-package
So, the `Package.swift` should be in the root. However, the empty file can be located anywhere.

**Comment by richardtop** [comment]
Please, let me know if there is anything preventing this pull request from being merged, I'm happy to make changes to get this finalized.

**Comment by nlohmann** [comment]
> However, the empty file can be located anywhere. Would you like me to relocate it somewhere?

is that file really needed?

**Comment by richardtop** [comment]
Yes, unfortunately, there is no way around it. I've added the comment about why that file is needed, it's a known limitation of the Swift Package Manager. Even Apple's official repositories use this approach: https://github.com/apple/swift-numerics/blob/main/Sources/_NumericsShims/_NumericsShims.c

**Comment by nlohmann** [comment]
I honestly do not like this. For Homebrew, I have a dedicated repository not to "spam" this repository: https://github.com/nlohmann/homebrew-json. Maybe this is a good approach also for the Swift package manager - especially if the file does not need to be updated with every release. What do you think?

**Comment by richardtop** [comment]
While I also don't like it, I'm not sure if this is possible with the current state of the SPM, as it expects `Package.swift` to be in the root of the repository.
Since it's known limitation, I'm pretty sure it'll be resolved in next versions of the SPM, since it's developing really fast.
On the other hand, not supporting SPM would complicate usage of this library for Apple platforms developers, as SPM is becoming the industry standard when managing dependencies for Apple apps.

**Comment by nlohmann** [comment]
I honestly do not like this solution. I am sorry that this is inconvenient for Apple users, but if every package manager dumps a few files to this repo, then it starts to get really ugly... Sorry.

**Comment by richardtop** [comment]
No problem, I understand. Apple users always have to think different✌️

**Pull request closed without merging**
