### PR TITLE
Fix examples/json_lines.cpp

### PR DESCRIPTION
**Pull request by x90nik**
The extra newline throws an exception.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
What is your exact error message? The code of `docs/examples/json_lines.cpp` compiles fine as-is.

**Comment by gregmarr** [comment]
The original report says it throws an exception, so I assume this is a runtime error, and the error is on the `json::parse` of an empty line after the last valid line.

**Comment by x90nik** [comment]
As `gregmarr` said, this is a runtime error.
Sorry, there is no problem with this example.
As you can see on the below snippet, I put 4 extra whitespaces before `)";` on 6th line.
I think this `exception` is related to the `<nlohmann/json.hpp>`'s core.
Should I have to open a `Bug Report` issue?
```cpp
int main() {
    input << R"({"name": "Gilbert", "wins": [["straight", "7♣"], ["one pair", "10♥"]]}
             {"name": "Alexa", "wins": [["two pair", "4♠"], ["two pair", "9♠"]]}
             {"name": "May", "wins": []}
             {"name": "Deloise", "wins": [["three of a kind", "5♣"]]} 
    )";

    try
    {
        while (std::getline(input, line))
        {
            std::cout << json::parse(line) << std::endl;
        }
    }
    catch (json::parse_error& ex)
    {
        std::cerr << "parse error at byte " << ex.byte << std::endl;
    }
}
```
```
{"name":"Gilbert","wins":[["straight","7ΓÖú"],["one pair","10ΓÖÑ"]]}
{"name":"Alexa","wins":[["two pair","4ΓÖá"],["two pair","9ΓÖá"]]}
{"name":"May","wins":[]}
{"name":"Deloise","wins":[["three of a kind","5ΓÖú"]]}
parse error at byte 5
```

**Comment by nlohmann** [comment]
Sorry: I meant I can compile and run the example as-is.

**Comment by gregmarr** [comment]
> Sorry: I meant I can compile and run the example as-is.

I can confirm the error with the blank line at the end: https://www.godbolt.org/z/3hzGz75WE

And now it's gone.  It was there a minute ago with the single newline at the end, but now it's not, it must have still been updating.  It's only there with two or more newlines at the end.

**Comment by gregmarr** [comment]
>As you can see on the below snippet, I put 4 extra whitespaces before )"; on 6th line.

Yeah, that's the source of the issue.  You changed from having a newline at the end of the data, which is handled cleanly, to having whitespace after the final newline, which does not get handled cleanly.  You'd need to strip leading whitespace from `line` before passing it to `json::parse()` if you wanted to support that.

**Comment by nlohmann** [comment]
Anything to do here then? And: if so, please create an PR for the `develop` branch and not the `gh-pages`.

**Pull request closed without merging**
