### PR TITLE
Hash pin only sensible workflows

### LINKED ISSUE #4058: Feat: hash pin github workflow dependencies
### Description

Hi again, I'd like to suggest another security practice recommended by the [OpenSSF Scorecard][scorecard-repo] which is to hash pin dependencies to prevent dependency-confusion, typosquatting and tag renaming attacks. Besides this is currently the only way to make your CI run as an immutable release.

The change would only be applied to GitHub workflows, dockerfiles and shell scripts dependencies.

This means:
- Hash pinning GitHub Workflow actions.
- Using --require-hashes on pip installs.

I can submit one PR for each type of change above to be easier to review if you prefer. Just let me know if that's the case.

Also it might be important to notice that the dependabot, that seems to be already enabled, is able to update both the hash and the comment version related to it.

Let me know if you are open to evaluate those changes and I'll submit the PR(s) ASAP. 

Any questions or concerns just let me know.
Thanks!

### Additional Context

A tag renaming attack is a type of attack whereby an attacker:
- Hijack an **action**.
- Upload a malicious version.
- Replace existing tags with malicious versions.

Both Dependency Confusion and Typosquatting attacks are more applicable to package managers (such as pip, npm, choco, etc)

A [dependency-confusion][deps-confusion] attack occurs when an attacker:
- Find the name of a package that the victims wants to install
- Create an identically named package and publish it under the public or default registry.
- Assign the package with a higher version number to trick the package manager tool to download it from the public repo.

 
A [typosquatting attack][typosquatting] is a type of attack whereby an attacker:
- Create a malicious package
- Publish it with a similar name of a known package (example: numpi instead of numpy)

[scorecard-repo]: https://github.com/ossf/scorecard
[deps-confusion]: https://www.websecuritylens.org/how-dependency-confusion-attack-works-and-how-to-prevent-it/ 
[typosquatting]: https://snyk.io/blog/typosquatting-attacks/ 

### Reproduction steps

None

#### Actions

Current
```yml
actions/checkout@v3
```

Expected
```yml
actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
```

#### Pip installs

Current
```yml
run: python -m pip install reuse
```

Expected
```yml
run: python -m pip install --require-hashes -r ci-deps.txt
```

### Minimal code example

```Shell
None
```

### Error messages

```Shell
None - not a bug
```

### Compiler and operating system

None

### Library version

None

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by joycebrum**
Closes #4058 

I've hash pinned only the workflows that had write permissions and configure the dependabot to run monthly. It may, from to time, suggest major updates on other workflows, but it you can use a "dependabot command" to make it not suggest that upgrade anymore.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
Now that the CI is green again on `develop`, can you please update this PR?

**Comment by joycebrum** [comment]
> Now that the CI is green again on `develop`, can you please update this PR?

Sure, done!

**Comment by nlohmann** [comment]
What about the other GitHub actions in `.github/workflows`?

**Comment by joycebrum** [comment]
> What about the other GitHub actions in `.github/workflows`?

Ah you mean upgrading the versions, I though it was just solving the merge conflicts, sorry. 
Done too.

**Comment by nlohmann** [comment]
FYI: I used https://app.stepsecurity.io/securerepo to create #4539.

**Comment by joycebrum** [comment]
> FYI: I used https://app.stepsecurity.io/securerepo to create #4539.

Nice! I'll close this then since it was already covered by #4539 
One note, if you ever want to reduce the number of dependabot PRs (if it is too frequent or numerous) you can do something similar to what I suggested in this PR:

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups: # group dependency updates all in a single PR
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /docs/mkdocs
    schedule:
      interval: daily
    groups:
      pypi:
        patterns: # group dependency updates all in a single PR
          - "*"

  - package-ecosystem: pip
    directory: /tools/serve_header
    schedule:
      interval: daily
    groups: # group dependency updates all in a single PR
      pip:
        patterns:
          - "*"
```

**Comment by nlohmann** [comment]
Sorry for the back and forth with this PR, and thanks for the hints. I did not know about pinning dependencies via hashes or how dependabot can be configured.

**Pull request closed without merging**
