### PR TITLE
Add pkg-config file

### PR DESCRIPTION
**Pull request by ericonr**
Add pkg-config generation to the CMake build system, functionally the same as the pkg-config generated by Meson. This PR is picking up on the work from #1701 .

* * *

## Pull request checklist

- [*]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [*]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.

### CODE REVIEW

**Comment by ericonr** [comment]
Done! Would you prefer I used `CMAKE_CURRENT_SOURCE_DIR` or `PROJECT_SOURCE_DIR` ?

**Comment by nlohmann** [comment]
I think CMAKE_CURRENT_SOURCE_DIR is less surprising.

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Added pkg-config file. #2253

* * *

**Comment by nlohmann** [comment]
FYI: The `DESCRIPTION` keyword for `project()` was only added in CMake 3.9. I will revert that part as we only required CMake 3.1.

**Comment by ericonr** [comment]
I see, thanks!

**Comment by eli-schwartz** [comment]
Somehow this managed to completely break `make install` when running tests, see #2318

**Pull request merged**
