### PR TITLE
Move Travis jobs to travis-ci.com

### PR DESCRIPTION
**Pull request by akbhuker**
Build Config file from travis.yml and update travis.yml file

### CODE REVIEW

**Review by nlohmann — COMMENTED** [review]
This seems to be a conversion from YAML to JSON - is this really required?

**Comment by akbhuker** [comment]
May be because JSON is often faster and is probably still interoperable with more systems

**Comment by akbhuker** [comment]
no, it is more than converting yml to json

**Comment by nlohmann** [comment]
> no, it is more than converting yml to json

What is it then? - it's hard to process the diff.

**Comment by akbhuker** [comment]
> > no, it is more than converting yml to json
> 
> What is it then? - it's hard to process the diff.

means i build jobs for that yml file

**Comment by nlohmann** [comment]
Can you explain the changes you made?

**Comment by akbhuker** [comment]
simply I build jobs on travis-cli.com and build config file and replace .travis.yml with build config file

**Comment by nlohmann** [comment]
What does it mean to "build jobs on travis-ci.com" and to "build a config file"? I do not understand what you did, nor do I understand the changes from the diff.

**Comment by akbhuker** [comment]
I did this 
Travis Jobs

**Comment by nlohmann** [comment]
This is a screenshot of a build. It does not explain the changes this PR proposes. I need to understand them before I can merge them.

**Comment by akbhuker** [comment]
I just change  .travis.yml file with build config

**Comment by nlohmann** [comment]
This PR is not needed any longer, see https://github.com/nlohmann/json/issues/2938#issuecomment-902636131.

**Pull request closed without merging**
