### PR TITLE
Add check if different version is also included

### PR DESCRIPTION
**Pull request by nlohmann**
Closes #3337

### CODE REVIEW

**Review by falbrechtskirchinger — APPROVED** [review]
Looks good to me. I hope you keep a checklist of all the places where the version number needs to be changed on release. ;-)

**Comment by nlohmann** [comment]
> Looks good to me. I hope you keep a checklist of all the places where the version number needs to be changed on release. ;-)

I will need to adjust https://github.com/nlohmann/json_release_scripts for this.

**Comment by falbrechtskirchinger** [comment]
> > Looks good to me. I hope you keep a checklist of all the places where the version number needs to be changed on release. ;-)
> 
> I will need to adjust https://github.com/nlohmann/json_release_scripts for this.

Oh good, you have a script. Slightly off-topic: I've been using `VER_TBD` as a version placeholder in the documentation in one of my branches. Would you be interested in adding something more formal to your scripts? Say `VER_NEXT` which could be replaced in the documentation and maybe selectively in source files (e.g., `JSON_HEDLEY_DEPRECATED(VER_NEXT)`, etc.)?

**Comment by mortenfyhn** [comment]
Fantastic!

**Pull request merged**
