### PR TITLE
Changes to clear warnings from MSVC 16.x

### LINKED ISSUE #1911: Compile warnings on MSVC 14.2
After upgrading from Visual Studio 17 to 19 i get the following compile warnings:

`Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).`
**.\nlohmann\detail\conversions\to_chars.hpp	993**
(also line 997, 1007, 1009, 1017, 1021, 1036 and 1038)

`Warning	C26444	Avoid unnamed objects with custom construction and destruction (es.84).`
**.\nlohmann\detail\input\json_sax.hpp	443**

`Warning	C28020	The expression '0<=_Param_(1)&&_Param_(1)<=400-1' is not true at this call.`
**.\nlohmann\detail\output\serializer.hpp	804**

`Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).`
**.\nlohmann\detail\output\serializer.hpp	810**

`Warning	C26495	Variable 'nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>::m_type' is uninitialized. Always initialize a member variable (type.6).`
**.\nlohmann\json.hpp	1777**

### PR DESCRIPTION
**Pull request by bhardwajs**
Fixes #1911

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by bhardwajs** [comment]
@nlohmann - Travis CI failed for XCode 9.3. It seems a transient failure. Is it possible to retry just that compiler? It's succeeded on other XCode versions.

**Comment by dota17** [comment]
Is it similar to #1967 ?

**Comment by bhardwajs** [comment]
@nlohmann - Let me know if you need anything from me for this PR. Thanks!

**Comment by nlohmann** [comment]
Can you please update to the latest `develop` branch? It seems that this issue is already solved.

**Pull request closed without merging**
