### PR TITLE
Implementation of get_ref()

### PR DESCRIPTION
**Pull request by dariomt**
As per discussion about issue #128

### CODE REVIEW

**Comment by nlohmann** [comment]
Hi @dariomt, thanks for the PR. Could you please have a look at the issues raised by Travis?

**Comment by dariomt** [comment]
The travis failures seem related to missing ```typename```

Hum... the error says:
```
error: need ‘typename’ before ‘std::add_pointer<ReferenceType>::type’ because ‘std::add_pointer<ReferenceType>’ is a dependent scope
   using PointerType = std::add_pointer<ReferenceType>::type;
```
I thought ```typename``` was not needed in a ```using``` context, because the compiler *knows* I'm asking for a type there! Doh!

I can only test my changes locally with MSVC. 
Is there a way to test my changes on clang/gcc remotely before making the PR?

**Comment by dariomt** [comment]
Trying to compile in VS2015 I get the errors shown in appveyor (```test\catch.hpp(1575): error C2056: illegal expression```)
It seems some change in catch.hpp is problematic :(
But this should be failing in master too!

**Comment by dariomt** [comment]
OK, now both clang and gcc are happy!  :)
I'll wait for #167 to be resolved before checking the MSVC status.

**Comment by nlohmann** [comment]
Thanks a lot!

**Pull request merged**
