### PR TITLE
Setup for inclusion in the Bazel Central Registry

### PR DESCRIPTION
**Pull request by fmeum**
By adding a MODULE.bazel file, this library becomes usable with Bazel's new external dependency management system Bzlmod.

The new tests are run when a new version is included in the Bazel Central Registry and verify that the basic functionality works with the provided Bazel setup.

See:
https://bazel.build/build/bzlmod

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [ ]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [ ]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
> ## 🔴 Amalgamation check failed! 🔴
> The source code has not been amalgamated. @fmeum Please read and follow the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

@falbrechtskirchinger The warning is odd - the sources have not been touched. Or do I miss anything?

**Comment by fmeum** [comment]
@nlohmann The amalgamation check appears to run the formatter on `tests` and my tests weren't properly formatted - should be fixed now.

**Comment by nlohmann** [comment]
My bad. Thanks for the quick response!

**Comment by fmeum** [comment]
I will leave this in draft until I have confirmed it works over at https://github.com/bazelbuild/bazel-central-registry/pull/248.

**Comment by fmeum** [comment]
@nlohmann I just noticed that https://github.com/nlohmann/json/pull/3709 is available at HEAD, but not in a published release. I will wait for the next release and pick this up once Bazel support is available in it.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/359 has added the module.

**Pull request closed without merging**
