### PR TITLE
patch android + gcc locale issue

### PR DESCRIPTION
**Pull request by headupinclouds**
SFINAE workaround for missing lconv support in Android (gcc + libstdc++)
See: https://github.com/fmtlib/fmt/commit/2fd6c0b24524f7ef107090d08cd86cdeb98fdac0

Discussion: https://github.com/nlohmann/json/issues/638#issuecomment-314079985
Note: Clang + libc++ should work (where available)

Returns the thousands separator for the current locale.  On android (gcc/libstdc++) the lconv structure is stubbed using an empty structure.  The test is for the size only, not for the presense of thousands_sep in std::lconv, because if one would add thousands_sep at some point, the size of structure would be at least sizeof(char*)

Ditto for decimal_point.

### CODE REVIEW

**Comment by headupinclouds** [comment]
Sorry!  I intended to send this to a fork.

**Comment by nlohmann** [comment]
Is this fix really necessary? As far as I remember, the locale issues with Android have been fixed.

**Comment by headupinclouds** [comment]
I believe such a patch is the only way to support an android-19 build target.  For such targets, the usual (frowned upon) `std::strto*` `std::stto*` namespace extensions, and explicit inclusion of `#include <cerrno>`, are also required prior to the the `#include <nlohmann/json.hpp>` line in the top level project.  These fixes work around the partial C++11 implementation and similar changes are required for a number of other C++11 packages.  It is clearly not a fault of `json`.  I use such a patch as a lifeline to keep android-19 build limping along until it can be abandoned and `libc++` is more stable.

Currently about 16% of devices still use KitKat: https://developer.android.com/about/dashboards/index.html#Platform

I expect a much larger number of applications use this as a minimum target.

### android-ndk-r10e/platforms/android-19/arch-arm/usr/include/locale.h
```
#if 1 /* MISSING FROM BIONIC - DEFINED TO MAKE libstdc++-v3 happy */
struct lconv { };
struct lconv *localeconv(void);
#endif /* MISSING */
```

### android-ndk-r10e/platforms/android-21/arch-arm//usr/include/locale.h
```
struct lconv {
    char* decimal_point;
    char* thousands_sep;
    char* grouping;
    char* int_curr_symbol;
    char* currency_symbol;
    char* mon_decimal_point;
    char* mon_thousands_sep;
    char* mon_grouping;
    char* positive_sign;
    char* negative_sign;
    char  int_frac_digits;
    char  frac_digits;
    char  p_cs_precedes;
    char  p_sep_by_space;
    char  n_cs_precedes;
    char  n_sep_by_space;
    char  p_sign_posn;
    char  n_sign_posn;
    char  int_p_cs_precedes;
    char  int_p_sep_by_space;
    char  int_n_cs_precedes;
    char  int_n_sep_by_space;
    char  int_p_sign_posn;
    char  int_n_sign_posn;
};
```

It is not defined until android-21.
```
android-ndk-r15b/platforms//android-9/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-12/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-13/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-14/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-15/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-16/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-17/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-18/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-19/arch-arm/usr/include/locale.h:struct lconv { };
android-ndk-r15b/platforms//android-21/arch-arm/usr/include/locale.h:struct lconv {   // defined
android-ndk-r15b/platforms//android-22/arch-arm/usr/include/locale.h:struct lconv {   // defined
android-ndk-r15b/platforms//android-23/arch-arm/usr/include/locale.h:struct lconv {   // defined
android-ndk-r15b/platforms//android-24/arch-arm/usr/include/locale.h:struct lconv {   // defined
android-ndk-r15b/platforms//android-26/arch-arm/usr/include/locale.h:struct lconv {   // defined
```

LLVM/Clang/libc++ was introduced in a Jellybean release.  This is the long term path for Android NDK development, but it is still lacking a number of features (I've encountered known `LTO` limitations) and it still has some stability problems.

android-ndk/ndk#379 (comment) # from a lead ndk dev in May

> libc++ is in much better shape than it was back then, but it's still not quite to the point that I'm comfortable recommending it. For a timeline on that, see our roadmap.

This patch may be quite Android specific at this time, but the SFINAE fix (borrowed from the fmt project) should be relatively transparent and I don't see any harm merging it.  I'm happy to resubmit or modify the PR if you have interest, but it is perfectly reasonable to leave such mods to project forks.  I sent this PR here by accident.

**Comment by headupinclouds** [comment]
This link provides a good high level summary of current Android NDK libc++ state and recommendations. 

https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md

Since this is an evolving document, and libc++ will eventually be a stable default, I thought it was appropriate to link the issue/roadmap directly in this PR for the record.

**Pull request closed without merging**
