### PR TITLE
Out of tree builds and a few other miscellaneous CMake cleanups.

### PR DESCRIPTION
**Pull request by ChrisKitching**
Addresses the stuff I raised in #241. Hopefully this isn't too invasive for you...

I'll attempt to find some time to do more cleanup in the coming days.

### CODE REVIEW

**Comment by nlohmann** [comment]
Hi @ChrisKitching, could you please check why the AppVeyor build is broken?

**Comment by nlohmann** [comment]
(Apart from this, I have not checked the details of the changes)

**Comment by ChrisKitching** [comment]
There we go. Builds on Windows are officially my least favourite thing.

**Comment by nlohmann** [comment]
Thanks!

**Pull request merged**
