### PR TITLE
Possibility to use without the dependency to file io and streams to use in intel sgx enclaves

### LINKED ISSUE #2728: Possibility to use without the dependency to file io and streams to use in intel sgx enclaves
I need to use your library in an intel sgx enclave. 
For security reasons it is not allowed to use file io there.

I created the pull request #2729 which includes some macros to be defined for using this great library without the file io.

### PR DESCRIPTION
**Pull request by theShmoo**
includes some macros to be defined for using without file io.

### CODE REVIEW

**Review by nlohmann — CHANGES_REQUESTED** [review]
Please run `make amalgamate` to make sure the single header is properly generated. The CI currently fails because this.

**Comment by nlohmann** [comment]
Sorry for the inactivity. I have one question left: you write in #2728 that the headers for I/O do not exist. But in your change you seem not to exclude any headers if `JSON_NO_IO` is defined.

**Comment by theShmoo** [comment]
Ah that is true!
The headers exist in Intels SGX implementation of the standard library. But they are empty:

for example in `iostream`: https://github.com/intel/linux-sgx/blob/master/sdk/tlibcxx/include/iostream

Should I remove the includes so that it also usable for other applications?

**Comment by nlohmann** [comment]
Yes, please. The use case may be still quite special, but at lease it would not assume include included headers are empty. I could imagine that that flag may be usable for some if they want to reduce compile times if they do not use I/O in their project.

**Comment by theShmoo** [comment]
Does the build pipeline fail because of me or is this an error in the pipeline?

**Comment by nlohmann** [comment]
This seems to be an issue in the pipeline. I need to investigate.

**Comment by nlohmann** [comment]
Please update the branch - I just merged #2817 to fix the CI.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by theShmoo** [comment]
Thank you very much for your support and your review!

**Comment by nlohmann** [comment]
Thanks!

**Pull request merged**
