### PR TITLE
Add .clang-format file

### PR DESCRIPTION
**Pull request by drodil**
Almost with same configuration used this far in the software. Minor changes here and there might occur in the formatting. If this is merged, I can create a new pull request that applies the formatting to existing source code.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](http://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

**Comment by nlohmann** [comment]
But why?

**Comment by drodil** [comment]
Just to keep the style of the source code similar between contributors. Also clang-format is supported by many IDEs and editors to do the formatting automatically when the file is saved. I think it's one of the best tools for C++ developers especially when there is lots of people working on the project. Makes code readable for everyone as soon as they get to know the syntax.

**Comment by nlohmann** [comment]
Sorry, but I am currently not planning to switch to Clang-Format, as it is not able to fully cover the current AStyle configuration.

**Comment by drodil** [comment]
Not sure what it cannot cover but sure, it's up to you :)

**Comment by nlohmann** [comment]
For instance, Clang-Format does not add braces to single-line else or case statements. You'd need Clang-Tidy on top of this. And if you apply your Clang-Format style, you'd see a difference to the status quo.

**Comment by nlohmann** [comment]
Thanks for your efforts, anyway!

**Pull request closed without merging**
