### PR TITLE
Fix 'const' qualifier on bool& has no effect

### PR DESCRIPTION
**Pull request by falbrechtskirchinger**
Disable the `to_json` overload for `std::vector<bool>::reference` when `std::vector<bool>::reference` is the same as `basic_json::boolean_t&`.

Thanks, @georgthegreat, for pointing out this issue.

Closes #3677.

### CODE REVIEW

**Comment by nlohmann** [comment]
Do we have a chance to add a regression test?

**Comment by falbrechtskirchinger** [comment]
Not without external dependencies. And the warning flag seems to be new.

**Comment by georgthegreat** [comment]
This does not work, unfortunately.
clang12 still issues a warning when he sees `const bool&`:

```
include/nlohmann/detail/conversions/to_json.hpp:274:39: error: 'const' qualifier on reference type 'std::vector<bool>::reference' (aka 'bool &') has no effect [-Werror,-Wignored-qualifiers]
inline void to_json(BasicJsonType& j, const std::vector<bool>::reference& b) noexcept
```

**Comment by falbrechtskirchinger** [comment]
Oh, that's because I made at least one mistake.

**Comment by georgthegreat** [comment]
Still no

```
include/nlohmann/detail/conversions/to_json.hpp:272:36: error: 'const' qualifier on reference type 'std::vector<bool>::reference' (aka 'bool &') has no effect [-Werror,-Wignored-qualifiers]
               std::is_convertible<const std::vector<bool>::reference&, typename BasicJsonType::boolean_t>::value
                                   ^~~~~~
include/nlohmann/detail/conversions/to_json.hpp:274:39: error: 'const' qualifier on reference type 'std::vector<bool>::reference' (aka 'bool &') has no effect [-Werror,-Wignored-qualifiers]
inline void to_json(BasicJsonType& j, const std::vector<bool>::reference& b) noexcept
```

**Comment by falbrechtskirchinger** [comment]
I could try flipping those checks, hoping the compiler short-circuits and doesn't get to the `is_convertible` check which seems to trigger the earning.

**Comment by georgthegreat** [comment]
And why const_reference fix proposed #3677 would not work?

**Comment by falbrechtskirchinger** [comment]
In the end, it would still conflict with the existing overload.

**Comment by falbrechtskirchinger** [comment]
One more try. I'm grasping at straws with this one. If it doesn't work, we may just have to suppress the warning for that function.

**Comment by georgthegreat** [comment]
It looks like the latter version will work for us.

Thanks, @falbrechtskirchinger!

**Comment by gregmarr** [comment]
Probably not a bad idea to also do the change from 3677 and use `const_reference`.

**Comment by falbrechtskirchinger** [comment]
No, that doesn't work. `::reference` and `::const_reference` are different types. In fact, `::const_reference` is `bool` in stdlibc++.

Assuming my last fix attempt works, I was going to give `::const_reference` the same treatment.

**Comment by falbrechtskirchinger** [comment]
I decided against dealing with `std::vector<bool>::const_reference` for now. Chances are, I'd make matters worse for everyone instead of fixing things for some hypothetical STL.

**Review by shaischaudhry — APPROVED** [review]

**Comment by falbrechtskirchinger** [comment]
And it turns out, that libc++ does use a different type for `const_reference`:
```
no known conversion from 'std::__1::vector<bool, std::__1::allocator<bool> >::const_reference' (aka '__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >')
```
Guess I'll have to add it after all.

**Comment by falbrechtskirchinger** [comment]
Let me walk you through the `enable_if` constraint:
Since we already have a `to_json` function for `BasicJsonType::boolean_t`, we need to disable the `vector<bool>::reference`/`vector<bool>::const_reference` overload, if:
* `vector<bool>::reference` is the same as `BasicJsonType::boolean_t &`, or
* `vector<bool>::const_reference`, stripped of cvref qualifiers, is the same as `BasicJsonType::boolean_t`.

This covers all tested and reported STLs.

**Review by falbrechtskirchinger — COMMENTED** [review]
Looks good to me.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Pull request merged**
