### PR TITLE
[Iterator] Adding the methods is_begin() and is_end() to the iter_impl

### PR DESCRIPTION
**Pull request by loumalouomega**
Hi,

I don't know if this is the proper way to proceed with a PR. Maybe I should create an issue first. I already created one some time ago https://github.com/nlohmann/json/issues/1242

After that I tried several things, the point is we create a iterator adaptor and we need to skip the end iterators during that creation process to avoid the assert.

 But after trying many things the only thing I could do to avoid the assert was creating this is_end() method.

Tell me if tis is not a proper solution to the problem or if you want me to implement a test for this methods that I added.

### CODE REVIEW

**Comment by nlohmann** [comment]
Why not check `it == j.begin()` instead of of `it.is_begin()`?

**Comment by loumalouomega** [comment]
Where I execute the code I cannot access to the whole "json list"

Here for example: 
https://github.com/KratosMultiphysics/Kratos/blob/8a1f314b960f9d6fd08172a03c3fa7ce6983f8db/kratos/includes/kratos_parameters.h#L162

**Comment by nlohmann** [comment]
I don't think this is a good addition as this is an extension to the usual iterator interface. If you need to know the container the iterator belongs to, then store a reference to it. As a PR may be the wrong place to discuss, please open an issue for this.

**Comment by loumalouomega** [comment]
I will try what you say (that I already tried but didn't work), if it doesn't solve the problem I will open an issue

Thanks

**Comment by loumalouomega** [comment]
Just to mention that I solved the problem, my error was that I was using a temporal container and the referenced value gave a memory error, now is properly solved. Sorry for the noise and thanks for the library

**Pull request closed without merging**
