### PR TITLE
Refacto/split basic json

### PR DESCRIPTION
**Pull request by theodelrieu**
Hi, I managed to move every nested struct/class present in `basic_json` to the `detail` namespace.

Excepted `json_pointer` which is now in `nlohmann`, I don't know if input/output adapters are exposed, if so, I will move them there too.

This is an intermediate refactoring, needed before splitting the library into multiple files, and before changing classes and namespace names.

I'm afraid the review will not be very interesting... I advise reviewers to look at each commit separately, it is not readable otherwise.

### CODE REVIEW

**Comment by theodelrieu** [comment]
It's weird that codacy only complains now, I did not change this code.

**Comment by theodelrieu** [comment]
I forgot to use the public API in every class i've split (except `parser` that became a friend, since it needs to modify `m_type/m_value` directly.

The tests passed because of the `#define private public` line present in almost each test file.

I think we should get rid of this line, it's quite dangerous when refactoring

**Comment by nlohmann** [comment]
I added this to allow for 100% coverage without changing the code. I'm not a fan of code refactoring just to simplify testing. I need to have a look at this PR when I'm home.

**Comment by theodelrieu** [comment]
Please note that the purpose of this PR is not to facilitate testing, but to prepare the split of `json.hpp`.

The main reason why this line exists is that we test **private nested classes'** public APIs. Once we split the code into multiple files, we'll be able to unit test each component public API directly, without decreasing today's coverage rate.

**Comment by nlohmann** [comment]
Sorry, i misunderstood. I shall have a look on Saturday.

**Comment by nlohmann** [comment]
Sorry, i misunderstood. I shall have a look on Saturday.

**Comment by theodelrieu** [comment]
It's weird, the `unit-cbor.cpp` file compiles on my laptop. I had to compile it by hand though, it seems it's not included when running `ninja`

**Comment by theodelrieu** [comment]
Finally I made that pass \o/

@nlohmann If you could take a look before pushing other commits, it'd be great (rebasing is horrible with all the code moving)

Also I won't be available for the next 2 weeks, so I can only make changes tonight (sorry for the rush :p)

**Comment by nlohmann** [comment]
Sorry for changing to much lately. I kind of forgot what it means to pending PRs...

**Comment by theodelrieu** [comment]
Thanks a lot! We shall talk about the next steps after I come back of vacations (I'll be available on slack during that time anyway)

The first thing should be quite trivial: splitting into multiple files, and add a cmake/makefile rule to amalgamate a single `json.hpp` file. Looking how Catch does that should be helpful.

The second is more hard, it's about the API breakage (namespace naming, single traits class, etc...) as discussed in #474.

I'll be happy to get on that issue when I come back!

**Comment by nlohmann** [comment]
Have a nice vacation!

**Pull request merged**
