### PR TITLE
Attempt to fix labeler permissions

### PR DESCRIPTION
**Pull request by falbrechtskirchinger**
Change trigger to `pull_request_target` for write permissions and limit permissions to minimum required.

### CODE REVIEW

**Comment by nlohmann** [comment]
The job seems not to be executed.

**Comment by falbrechtskirchinger** [comment]
I don't think this will trigger until it's merged.

Testing here. I've pushed it to `develop` and submitted a PR. (Of course, we have the same issue of not being able to test permissions this way.)
https://github.com/falbrechtskirchinger/json/pull/1

**Comment by falbrechtskirchinger** [comment]
All I can say is that it runs (once merged). If it improves the situation over the status-quo of not labeling PRs, I don't know.

**Comment by nlohmann** [comment]
Let's give it a try!

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Pull request merged**
