### PR TITLE
Doctest 2.4.8

### PR DESCRIPTION
**Pull request by nlohmann**
This PR updates Doctest to the latest version 2.4.8.

### CODE REVIEW

**Comment by nlohmann** [comment]
Test fail for MSVC 2015. See https://github.com/doctest/doctest/issues/573 for bug report.

**Comment by nlohmann** [comment]
The bug was resolved in Doctest 2.4.8.

**Comment by gregmarr** [comment]
That's a lot of clang tidy suppressing.  Is there a way to specify those just for the test directory?

**Comment by nlohmann** [comment]
> That's a lot of clang tidy suppressing. Is there a way to specify those just for the test directory?

I have no idea. I am only aware of suppressing warnings in the code via `// NOLINT` comments.

I currently just want to make it pass the CI. I will create an issue upstream to inform the Doctest maintainers that their latest release triggers these warnings.

**Comment by gregmarr** [comment]
I wonder if it would make sense to exclude the tests from clang tidy.  https://github.com/nlohmann/json/blob/1aca6cb949f4595994ba5e5188682416d3058688/cmake/ci.cmake#L635

**Comment by nlohmann** [comment]
It would be great to only exclude file `doctest.h` from the results. I have not found a way to do this, and I also have not found a way to check the header without adding Clang-Tidy to the compilation process of the test suite.

**Comment by nlohmann** [comment]
Blocked until https://github.com/doctest/doctest/issues/607 is addressed.

**Comment by nlohmann** [comment]
We'll wait until Doctest 2.4.9 (see https://github.com/doctest/doctest/issues/607#issuecomment-1146950377).

**Pull request closed without merging**
